# Generated by Django 5.0.3 on 2024-04-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0003_language_alter_characteristic_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='script',
            field=models.CharField(choices=[('giants', 'Великанья'), ('dwarven', 'Дварфская'), ('common', 'Общая'), ('elvish', 'Эльфийская'), ('infernal', 'Инфернальная'), ('draconic', 'Драконья'), ('celestial', 'Небесная'), ('-', 'Отсутствует')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='speakers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='type',
            field=models.CharField(choices=[('ethnic', 'Этнические языки'), ('exotic', 'Экзотические языки'), ('secret', 'Тайные языки')], max_length=50, null=True),
        ),
    ]
