# Generated by Django 5.0.3 on 2024-04-06 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0005_section_source_characteristic_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='characteristics', to='knowledge_base.section'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='characteristics', to='knowledge_base.source'),
        ),
        migrations.AlterField(
            model_name='language',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='languages', to='knowledge_base.section'),
        ),
        migrations.AlterField(
            model_name='language',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='languages', to='knowledge_base.source'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='skills', to='knowledge_base.section'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='skills', to='knowledge_base.source'),
        ),
    ]
