# Generated by Django 5.0.3 on 2024-04-08 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0006_alter_characteristic_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('rate', models.DecimalField(decimal_places=1, max_digits=4)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coins', to='knowledge_base.section')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coins', to='knowledge_base.source')),
            ],
            options={
                'verbose_name': 'Coin',
                'verbose_name_plural': 'Coins',
                'db_table': 'coins',
                'ordering': ['rate'],
            },
        ),
        migrations.CreateModel(
            name='Die',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dice', to='knowledge_base.section')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dice', to='knowledge_base.source')),
            ],
            options={
                'verbose_name': 'Die',
                'verbose_name_plural': 'Dice',
                'db_table': 'dice',
                'ordering': ['title'],
            },
        ),
    ]
