# Generated by Django 5.0.3 on 2024-04-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0007_coin_die'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='short_title',
            field=models.CharField(default=4, max_length=5),
            preserve_default=False,
        ),
    ]
