# Generated by Django 5.0.3 on 2024-04-08 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0009_die_modifier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='die',
            options={'ordering': ['modifier'], 'verbose_name': 'Die', 'verbose_name_plural': 'Dice'},
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characteristics', to='knowledge_base.section'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characteristics', to='knowledge_base.source'),
        ),
        migrations.AlterField(
            model_name='language',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='languages', to='knowledge_base.section'),
        ),
        migrations.AlterField(
            model_name='language',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='languages', to='knowledge_base.source'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='characteristic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='knowledge_base.characteristic'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='knowledge_base.section'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='knowledge_base.source'),
        ),
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alignments', to='knowledge_base.section')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alignments', to='knowledge_base.source')),
            ],
            options={
                'verbose_name': 'Alignment',
                'verbose_name_plural': 'Alignments',
                'db_table': 'alignments',
                'ordering': ['pk'],
            },
        ),
    ]
